---
name: build

on:
  push:
    branches: ["main"]
    tags: ["v*"]
    paths:
      - .github/workflows/*.yml
      - "**/*.go"
      - go.*
      - .golangci.yaml
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/*.yml
      - "**/*.go"
      - go.*
      - Makefile
      - .golangci.yaml

jobs:
  golang-security:
    uses: andreygrechin/github-actions/.github/workflows/golang-security.yml@main
    permissions:
      contents: read
      pull-requests: read
    with:
      go-version: "1.24.x"

  lint:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.24.x"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: go vet
        run: go vet ./...

      - uses: dominikh/staticcheck-action@v1
        with:
          install-go: false
          version: latest

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
          args: --show-stats

  build:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.24.x"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          go get .

      - name: Build
        run: |
          make build

      - name: Test
        run: go test -coverprofile=coverage.txt -v ./...

    # - name: Upload coverage reports to Codecov
    #   uses: codecov/codecov-action@v5
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
